#!usr/bin/env bash
# installing nginx on web server

sudo apt-get update
sudo apt-get install nginx

echo "Hello World" | sudo tee /var/www/html/index.html

sudo nginx restart

sudo service nginx reload
