#!/usr/bin/env bash
#configures a new Ubuntu machine nginx
sudo apt-get update
sudo apt-get install haproxy
echo "frontend web-front
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server web1 35.227.47.184:80 check
        server web2 35.190.188.208:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
